services:
  api:
    container_name: backend
    hostname: be-py
    build: .
    restart: always           # 常に再起動
    working_dir: '/workspace' # デフォルトの作業ディレクトリ
    tty: true                 # コンテナを終了させずに待たせる
    volumes:                  # ホストとゲストのディレクトリを紐づける
      - type: bind            # ホストのディレクトリをゲストにマウントさせる
        source: ../workspace  # ホストの`workspace`ディレクトリを指定
        target: /workspace    # ゲストの`/workspace`にマウントさせる
      - .dockervenv:workspace/src/.venv
      - .:workspace/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
